# Generated by Django 6.0.3 on 2026-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('foto_url', models.URLField(max_length=500)),
                ('foto_shiny', models.URLField(blank=True, max_length=500)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('hp', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defesa', models.IntegerField()),
                ('ataque_especial', models.IntegerField()),
                ('defesa_especial', models.IntegerField()),
                ('velocidade', models.IntegerField()),
                ('tipos', models.ManyToManyField(related_name='pokemons', to='Pokedex.tipo')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémons',
                'ordering': ['numero'],
            },
        ),
    ]
